type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Category @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  description: String
}

type Expense @table {
  user: User!
  category: Category
  amount: Float!
  date: Date!
  description: String!
  createdAt: Timestamp!
}

type Budget @table {
  user: User!
  category: Category
  limitAmount: Float!
  startDate: Date!
  endDate: Date!
  createdAt: Timestamp!
}